### ISSUE TITLE
Path to europarl text data

### ISSUE THREAD

**Issue by abhi1nandy2** [TimotheeMickus/bert-splat#1]
https://github.com/TimotheeMickus/bert-splat/blob/main/linear_structure.py#L1127 - 
Could you please share the link to `europarl-sample.txt`?

**Comment by TimotheeMickus** [comment]
Not sure I kept the exact sample, I'll check if I can find it back on Monday. 

As the name suggest, it was a random sample of 10K sentences from EuroParl which you can get [here](https://www.statmt.org/europarl/v7/). I most likely filtered out metadata first (stuff like speaker info).

**Comment by abhi1nandy2** [comment]
Thanks! It would be great if you could provide the sample, or a way to get that (e.g. some preprocessing code).

**Comment by TimotheeMickus** [comment]
You can try something like that:
```
wget https://www.statmt.org/europarl/v7/europarl.tgz
tar xzvf europarl.tgz txt/en/
cat txt/en/*.txt | grep -v -e '<' -e '>' | grep [a-zA-Z] | sort -u |  shuf | head -10000 > europarl-sample.txt
```

**Comment by TimotheeMickus** [comment]
Couldn't find the original sample, sorry. The command above should yield something comparable though.
